id: editor
permissions:
  - 'use varbase_editorial_workflow transition archive'
  - 'use varbase_editorial_workflow transition create_new_draft'
  - 'use varbase_editorial_workflow transition publish'
  - 'use varbase_editorial_workflow transition archived_published'
  - 'use varbase_editorial_workflow transition review'
  - 'use varbase_simple_workflow transition archive'
  - 'use varbase_simple_workflow transition create_new_draft'
  - 'use varbase_simple_workflow transition publish'
  - 'use varbase_simple_workflow transition archived_published'
  - 'view any unpublished content'
  - 'view latest version'
  - 'use moderation sidebar'
  - 'schedule publishing of nodes'
  - 'view scheduled content'
